/* eslint-disable @typescript-eslint/naming-convention */
import { Colors, VsTheme } from "../types";
import dark from '../colors/dark.json';

function getColors(theme: string): Colors {
    switch (theme) {
        case 'gipsy-dark':
            return dark;
        default:
            throw new Error(`Colors for "${theme}" not found!`);
    }
}

export function generateTheme(theme: string, name: string, type?:string): VsTheme {

    const colors = getColors(theme);

    return {
        name: `${name}`,
        id: `${theme}`,
        type: `${type}`,
        author: 'Luca Gärisch',
        colors: {
            "activityBar.activeFocusBorder": colors.accent,
            "activityBar.background": colors.bg.primary,
            "activityBar.border": colors.bg.primary,
            "activityBar.foreground": colors.accent,
            "activityBar.inactiveForeground": colors.fg.muted,
            "activityBarBadge.background": colors.accent,
            "activityBarBadge.foreground": colors.base.black,

            "debugConsole.errorForeground": colors.base.red,
            "debugConsole.infoForeground": colors.base.cyan,
            "debugConsole.sourceForeground": colors.base.white,
            "debugConsole.warningForeground": colors.base.orange,
            "debugConsoleInputIcon.foreground": colors.base.yellow,
            "debugExceptionWidget.background": colors.bg.tertiary,
            "debugExceptionWidget.border": colors.bg.overlay,
            "debugIcon.breakpointCurrentStackframeForeground": colors.base.yellow,
            "debugIcon.breakpointDisabledForeground": colors.fg.darkend,
            "debugIcon.breakpointForeground": colors.base.red,
            "debugIcon.breakpointStackframeForeground": colors.base.white,
            "debugIcon.breakpointUnverifiedForeground": colors.base.orange,
            "debugIcon.continueForeground": colors.base.white,
            "debugIcon.disconnectForeground": colors.base.white,
            "debugIcon.pauseForeground": colors.base.white,
            "debugIcon.restartForeground": colors.base.green,
            "debugIcon.startForeground": colors.base.green,
            "debugIcon.stepBackForeground": colors.base.white,
            "debugIcon.stepIntoForeground": colors.base.white,
            "debugIcon.stepOutForeground": colors.base.white,
            "debugIcon.stepOverForeground": colors.base.white,
            "debugIcon.stopForeground": colors.base.red,
            "debugTokenExpression.boolean": colors.base.orange,
            "debugTokenExpression.error": colors.base.red,
            "debugTokenExpression.name": colors.base.cyan,
            "debugTokenExpression.number": colors.base.magenta,
            "debugTokenExpression.string": colors.base.yellow,
            "debugTokenExpression.value": colors.base.white,
            "debugToolBar.background": colors.bg.tertiary,
            "debugView.exceptionLabelBackground": colors.base.red,
            "debugView.exceptionLabelForeground": colors.bg.overlay,
            "debugView.stateLabelBackground": colors.base.green,
            "debugView.stateLabelForeground": colors.bg.overlay,
            "debugView.valueChangedHighlight": colors.base.yellow,

            "dropdown.background": colors.bg.overlay,
            "dropdown.border": colors.transparent,
            "dropdown.foreground": colors.fg.base,
            "dropdown.listBackground": colors.bg.overlay,

            "editor.background": colors.bg.primary,
            "editor.foreground": colors.fg.base,
            "editor.lineHighlightBorder": colors.transparent,
            "editor.selectionHighlichtBorder": colors.transparent,
            "editor.wordHighlightBorder": colors.transparent,
            "editor.wordHighlightStrongBorder": colors.transparent,
            "editorBracketHighlight.foreground1": colors.base.red,
            "editorBracketHighlight.foreground2": colors.base.orange,
            "editorBracketHighlight.foreground3": colors.base.magenta,
            "editorBracketHighlight.foreground4": colors.base.green,
            "editorBracketHighlight.foreground5": colors.base.cyan,
            "editorBracketHighlight.foreground6": colors.base.yellow,
            "editorCursor.foreground": colors.fg.base,
            "editorError.background": colors.transparent,
            "editorError.border": colors.transparent,
            "editorError.foreground": colors.base.red,
            "editorGroupHeader.noTabsBackground": colors.bg.secondary,
            "editorGroupHeader.tabsBackground": colors.bg.secondary,
            "editorGroupHeader.tabsBorder": colors.transparent,
            "editorGutter.addedBackground": colors.base.green,
            "editorGutter.background": colors.bg.primary,
            "editorGutter.deletedBackground": colors.base.red,
            "editorGutter.foldingControlForeground": colors.fg.muted,
            "editorGutter.modifiedBackground": colors.base.orange,
            "editorInfo.foreground": colors.base.cyan,
            "editorLightBulb.foreground": colors.base.yellow,
            "editorLightBulbAutoFix.foreground": colors.base.green,

            "extensionBadge.remoteForeground": colors.accent,
            "extensionBadge.remoteBackground": colors.bg.primary,
            "extensionButton.prominentBackground": colors.bg.primary,
            "extensionButton.prominentForeground": colors.fg.base,
            //"extensionButton.prominentHoverBackground": ,
            "extensionIcon.preReleaseForeground": colors.base.magenta,
            "extensionIcon.sponsorForeground": colors.base.cyan,
            "extensionIcon.starForeground": colors.base.yellow,
            "extensionIcon.verifiedForeground": colors.base.green,

            "focusBorder": colors.bg.tertiary,
            "foreground": colors.fg.base,

            "gitDecoration.addedResourceForeground": colors.git.added,
            //"gitDecoration.conflictingResourceForeground": ,
            "gitDecoration.deletedResourceForeground": colors.git.deleted,
            "gitDecoration.ignoredResourceForeground": colors.git.ignored,
            "gitDecoration.modifiedResourceForeground": colors.git.modified,
            "gitDecoration.stageDeletedResourceForeground": colors.git.deleted,
            "gitDecoration.stageModifiedResourceForeground": colors.git.modified,
            "gitDecoration.untrackedResourceForeground": colors.git.untracked,

            "notificationCenter.border": colors.transparent,
            "notificationCenterHeader.background": colors.bg.overlay,
            "notificationCenterHeader.foreground": colors.fg.muted,
            "notificationLink.foreground": colors.accent,
            "notifications.background": colors.bg.overlay,
            "notifications.border": colors.transparent,
            "notifications.foreground": colors.fg.muted,
            "notificationsErrorIcon.foreground": colors.base.red,
            "notificationsInfoIcon.foreground": colors.base.blue,
            "notificationsWarningIcon.foreground": colors.base.orange,
            "notificationToast.border": colors.transparent,

            "panel.background": colors.bg.primary,
            "panel.border": colors.bg.tertiary,
            //"panel.dropBackground": ,
            "panelTitle.activeBorder": colors.accent,
            "panelTitle.activeForeground": colors.accent,
            "panelTitle.inactiveForeground": colors.fg.darkend,

            "problemsErrorIcon.foreground": colors.base.red,
            "problemsInfoIcon.foreground": colors.base.blue,
            "problemsWarningIcon.foreground": colors.base.orange,

            "settings.checkboxBackground": colors.bg.secondary,
            "settings.checkboxBorder": colors.bg.overlay,
            "settings.checkboxForeground": colors.base.green,
            "settings.dropdownBackground": colors.bg.secondary,
            "settings.dropdownBorder": colors.bg.overlay,
            "settings.dropdownForeground": colors.fg.base,
            "settings.dropdownListBorder": colors.bg.overlay,
            "settings.headerForeground": colors.accent,
            "settings.modifiedItemForeground": colors.accent,
            "settings.modifiedItemIndicator": colors.accent,
            "settings.numberInputBackground": colors.bg.secondary,
            "settings.numberInputBorder": colors.bg.overlay,
            "settings.numberInputForeground": colors.fg.base,
            //"settings.rowHoverBackground": ,
            "settings.textInputBackground": colors.bg.secondary,
            "settings.textInputBorder": colors.bg.overlay,
            "settings.textInputForeground": colors.fg.base,

            "sideBar.background": colors.bg.secondary,
            "sideBar.border": colors.bg.primary,
            //"sideBar.dropBackground": ,
            "sideBar.foreground": colors.fg.darkend,
            "sideBarSectionHeader.background": colors.bg.secondary,
            "sideBarSectionHeader.foreground": colors.fg.darkend,
            "sideBarTitle.foreground": colors.fg.muted,

            "statusBar.background": colors.bg.primary,
            "statusBar.border": colors.transparent,
            "statusBar.debuggingBackground": colors.bg.tertiary,
            "statusBar.debuggingBorder": colors.bg.primary,
            "statusBar.debuggingForeground": colors.fg.base,
            "statusBar.focusBorder": colors.transparent,
            "statusBar.foreground": colors.fg.darkend,
            "statusBar.noFolderBackground": colors.bg.primary,
            "statusBar.noFolderBorder": colors.transparent,
            "statusBar.noFolderForeground": colors.fg.darkend,
            "statusBarItem.activeBackground": colors.bg.overlay,
            "statusBarItem.errorBackground": colors.bg.primary,
            "statusBarItem.errorForeground": colors.base.red,
            "statusBarItem.focusBorder": colors.transparent,
            //"statusBarItem.hoverBackground": ,
            //"statusBarItem.prominentBackground": ",
            //"statusBarItem.prominentHoverBackground": ,
            "statusBarItem.remoteBackground": colors.bg.primary,
            "statusBarItem.remoteForeground": colors.accent,

            "tab.activeBackground": colors.bg.primary,
            "tab.activeBorder": colors.accent,
            "tab.activeForeground": colors.accent,
            "tab.activeModifiedBorder": colors.bg.tertiary,
            "tab.border": colors.transparent,
            "tab.hoverBackground": colors.bg.primary,
            "tab.hoverBorder": colors.bg.tertiary,
            "tab.hoverForeground": colors.fg.base,
            "tab.inactiveBackground": colors.bg.secondary,
            "tab.inactiveForeground": colors.fg.muted,
            "tab.inactiveModifiedBorder": colors.bg.tertiary,
            "tab.lastPinnedBorder": colors.bg.tertiary,
            "tab.unfocusedActiveBorder": colors.fg.darkend,
            "tab.unfocusedActiveForeground": colors.fg.muted,
            "tab.unfocusedActiveModifiedBorder": colors.bg.tertiary,
            "tab.unfocusedHoverBackground": colors.bg.primary,
            "tab.unfocusedHoverBorder": colors.transparent,
            "tab.unfocusedHoverForeground": colors.fg.muted,
            "tab.unfocusedInactiveForeground": colors.fg.darkend,
            "tab.unfocusedInactiveModifiedBorder": colors.bg.tertiary,

            "textLink.activeForeground": colors.fg.base,
            "textLink.foreground": colors.accent,

            "titleBar.activeBackground": colors.bg.primary,
            "titleBar.activeForeground": colors.fg.muted,
            "titleBar.border": colors.bg.primary,
            "titleBar.inactiveBackground": colors.bg.primary,
            "titleBar.inactiveForeground": colors.fg.darkend,

            "walkThrough.embeddedEditorBackground": colors.bg.secondary,

            "welcomePage.buttonBackground": colors.bg.tertiary,
            //"welcomePage.buttonHoverBackground": ,
            "welcomePage.progress.background": colors.bg.tertiary,
            "welcomePage.progress.foreground": colors.accent,
            //"welcomePage.titleBackground": ,
        }
    };
}